services:
  blod-backend:
    build: ./backend
    container_name: BLOD-backend
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/healthcloud?authSource=admin
      - DB_NAME=healthcloud
      - PORT=5005
    depends_on:
      - blod-mongodb
    networks:
      - app-network

  blod-frontend:
    build: ./frontend/blod
    container_name: BLOD-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - blod-backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:5005

  blod-mongodb:
    image: mongo:4.4.6
    container_name: blod-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./backend/mongo_data:/data/db
      - ./backend/mongo_data:/mongo_data
      - ./backend/mongo_data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.s
    networks:
      - app-network

volumes:
  mongo_data:
  python_service_data:

networks:
  app-network:
    driver: bridge